excluded:
- Pods
- ThirdParty
# SwiftLint has trouble with these files. See <https://github.com/realm/SwiftLint/issues/3988>.
disabled_rules:
- block_based_kvo
- cyclomatic_complexity
- file_length
- for_where
- force_cast
- force_try
- function_body_length
- function_parameter_count
- identifier_name
- line_length
- multiple_closures_with_trailing_closure
- nesting
- no_fallthrough_only
- notification_center_detachment
- todo
- type_body_length
- unneeded_synthesized_initializer
- unused_closure_parameter
- trailing_comma
opt_in_rules:
- comma_inheritance
- empty_string
- sorted_first_last
inclusive_language:
  override_allowed_terms: ["master", "whitelist"]
large_tuple:
  warning: 4
  error: 4
type_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 500
    error: 500
  excluded:
  - Id
  allowed_symbols: ["_"]
